
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '79640A0E165896814A2ADB212E0658F8'
    
_lr_action_items = {'INTEGER':([0,],[2,]),'DOM':([13,],[14,]),'WINE':([13,],[15,]),'RANK':([0,],[3,]),'.':([2,],[13,]),'$end':([0,1,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,],[-11,-6,-10,-2,-9,0,-5,-3,-8,-1,-7,-4,-16,-12,-13,-18,-14,-17,-15,]),'CHATEAU':([13,],[16,]),'DOMAINE':([13,],[18,]),'TENUTA':([13,],[17,]),'OPUS':([13,],[19,]),'PETRUS':([13,],[20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'empty':([0,],[8,]),'chateau':([0,],[12,]),'opus':([0,],[9,]),'rank':([0,],[4,]),'wine':([0,],[10,]),'dom':([0,],[11,]),'petrus':([0,],[1,]),'tenuta':([0,],[5,]),'start':([0,],[6,]),'domaine':([0,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> wine','start',1,'p_start','Project5.py',44),
  ('start -> rank','start',1,'p_start','Project5.py',45),
  ('start -> empty','start',1,'p_start','Project5.py',46),
  ('start -> chateau','start',1,'p_start','Project5.py',47),
  ('start -> domaine','start',1,'p_start','Project5.py',48),
  ('start -> petrus','start',1,'p_start','Project5.py',49),
  ('start -> dom','start',1,'p_start','Project5.py',50),
  ('start -> opus','start',1,'p_start','Project5.py',51),
  ('start -> tenuta','start',1,'p_start','Project5.py',52),
  ('rank -> RANK','rank',1,'p_rank','Project5.py',55),
  ('empty -> <empty>','empty',0,'p_empty','Project5.py',59),
  ('wine -> INTEGER . WINE','wine',3,'p_wine','Project5.py',63),
  ('chateau -> INTEGER . CHATEAU','chateau',3,'p_chateau','Project5.py',67),
  ('domaine -> INTEGER . DOMAINE','domaine',3,'p_domaine','Project5.py',71),
  ('petrus -> INTEGER . PETRUS','petrus',3,'p_petrus','Project5.py',75),
  ('dom -> INTEGER . DOM','dom',3,'p_dom','Project5.py',79),
  ('opus -> INTEGER . OPUS','opus',3,'p_opus','Project5.py',83),
  ('tenuta -> INTEGER . TENUTA','tenuta',3,'p_tenuta','Project5.py',87),
]
